twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        navigation: '@App\Service\Navigation'
        app_url: '%env(APP_URL)%'

when@test:
    twig:
        strict_variables: true
