###########################################
# Start working in a dedicated build image
###########################################
FROM registry-mt1.enjoy-platform.net/silverspin/composer-npm-fragment-php74:4 as builder-image
WORKDIR /var/www/platform

###########################################
# Use that image as installer for packages
###########################################
FROM builder-image as installer

# Install Node packages
COPY package* ./
RUN npm install

###########################################
# Use installer image to compile node stuff
###########################################
FROM installer as compiler

# Copy over all source files, and build node files
# Will use .dockerignore to skip copying some files
COPY . .
RUN npm run build

###########################################
# Move to dedicated run image
###########################################
FROM registry-mt1.enjoy-platform.net/base-images/redhat-nginx:1.14
COPY --from=compiler /var/www/platform/public /opt/app-root/src/platform/public
