apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: boilerplate-fragment

resources:
  - ../shared-configs/fragment/base

patchesStrategicMerge:
  - patch-deployment-images.yaml
  - patch-deployment-readiness.yaml
