apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragment
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: boilerplate-fragment-frontend
        # This will hit the /ping route on Symfony, confirming that the
        # connection from nginx -> php-fpm -> symfony works. This is a
        # bit of a layering violation and is subject to change in the
        # future.
        readinessProbe:
          httpGet:
            path: /ping
            port: 8081
            scheme: HTTP
